version: "3.8"
services:
  datadownload:
    build:
      context: .
      dockerfile: Dockerfile
    image: $IMAGE_ID
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      R_CONFIG_ACTIVE: docker
      FRED_KEY: ${FRED_KEY}
  shinyappsdeploy:
    # deploy the app to shinyapps and download and process the data.
    build:
      context: .
      dockerfile: DockerfileDeployShinyApps
    environment:
      DATA_DIR: /data
      PROJECT_ROOT: /Rscripts
      FRED_KEY: ${FRED_KEY}
      SHINYAPPS_SECRET: ${SHINYAPPS_SECRET}
      SHINYAPPS_TOKEN: ${SHINYAPPS_TOKEN}
      SHINYAPPS_ACCOUNT: ${SHINYAPPS_ACCOUNT}
    command: >
      bash -c "/Rscripts/unemploymentDataProcessor.R && /Rscripts/deployShinyApps.R"
    volumes:
      - type: bind
        source: ./data
        target: /data
  shinyappsdeploywithrelease:
    # deploy the app to shinyapps using the github-released version of the data.
    # (this does not download the release - it assumes the release is present)
    build:
      context: .
      dockerfile: DockerfileDeployShinyApps
    environment:
      R_CONFIG_ACTIVE: docker
      FRED_KEY: ${FRED_KEY}
      SHINYAPPS_SECRET: ${SHINYAPPS_SECRET}
      SHINYAPPS_TOKEN: ${SHINYAPPS_TOKEN}
      SHINYAPPS_ACCOUNT: ${SHINYAPPS_ACCOUNT}
    command: /Rscripts/deployShinyApps.R
    volumes:
      - type: bind
        source: ./data
        target: /data
volumes:
  data:
