# Workflow to build a docker image that can be used to download and process unemployment data.
#
# Other workflows use this image to either publish the data or to collect the data and then
# publish the web app.
name: Build docker image to download unemployment data
on: [push]
env:
  IMAGE_NAME: uidatadownloader
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image to download unemployment data.
        run: docker build . --tag $IMAGE_NAME
      - name: Log into registry
        run: |
          # github automatically creates the GITHUB_TOKEN token. 
          # see https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token  
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
      - name: Push to registry
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "$default-branch" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
