# Workflow to download and process unemployment data and then deploy the app to shinyapps.io

# Do this by running the ui-explorer container with a CMD that calls the r script that deploys the app. (and overrides the default r script that
#   processes the data. )
name: Deploy ui-explorer to shinyapps.io
on: [push] # when complete, run this when the 'release data' workflow completes,  https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
env:
  IMAGE_NAME: uidatadownloader
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy ui-explorer to shinyapps.io
    steps:
      - name: Setup repository
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . --tag $IMAGE_NAME
      - name: Run docker with CMD set to run the script that deploys the app.
        env:
          DATA_DIR: /data
          PROJECT_ROOT: /Rscripts
          FRED_KEY: ${{secrets.FRED_KEY}}
          SHINYAPPS_SECRET: ${{secrets.SHINYAPPS_SECRET}}
          SHINYAPPS_TOKEN: ${{secrets.SHINYAPPS_TOKEN}}
          SHINYAPPS_ACCOUNT: ${{secrets.SHINYAPPS_ACCOUNT}}
        run: docker-compose run --rm shinyappdeploy
