# Workflow to pull the datadownload docker image, run it, and store the created data.
name: Process unemployment data and publish
on: [push]
env:
  IMAGE_ID: clsphila/ui-data-explorer/uidatadownloader:dockerize-update-2020
  FRED_KEY: ${{secrets.FRED_KEY}}
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    name: Download Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download and process data
        run: |
          docker-compose run --rm datadownload
      - name: Create release, or update if necessary.
        run: . ./updateRelease.sh
